# Generated by Django 6.0.6 on 2026-06-18 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, default='fa-folder', help_text='Classe Font Awesome, ex: fa-book', max_length=60)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thème wiki',
                'verbose_name_plural': 'Thèmes wiki',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoriemacro',
            options={'ordering': ['nom'], 'verbose_name': 'Catégorie de macro', 'verbose_name_plural': 'Catégories de macros'},
        ),
        migrations.AlterModelOptions(
            name='macro',
            options={'ordering': ['titre'], 'verbose_name': 'Macro'},
        ),
        migrations.AddField(
            model_name='macro',
            name='date_modif',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('contenu_md', models.TextField(help_text='Contenu en Markdown (titres, listes, code, etc.)')),
                ('resume', models.CharField(blank=True, help_text="Résumé court affiché dans la card d'accueil (auto-généré si vide)", max_length=300)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.theme')),
            ],
            options={
                'verbose_name': 'Article wiki',
                'verbose_name_plural': 'Articles wiki',
                'ordering': ['-date_modif'],
            },
        ),
    ]
